In [2]:
import numpy as np #core feature of numpy is array

In [3]:
np.__version__

'2.3.1'

## Create & Read

#### 1D Array

In [ ]:
## or #### esc m shift+enter

In [12]:
arr1= np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr1)

numpy.ndarray

In [14]:
arr1.shape

(6,)

In [8]:
arr1.dtype

dtype('int64')

In [9]:
arr1.ndim

1

In [13]:
arr1.size

6

#### 2D Array

In [16]:
arr2=np.array([[1,4,5],[6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [17]:
arr2.ndim

2

In [18]:
arr2.shape #(row,col)

(2, 3)

In [19]:
arr2.dtype

dtype('int64')

In [22]:
arr2.size

6

#### 3D Array

In [29]:
arr3=np.array([[[1,4,5],[6,7,4]], [[3,5,4],[5,8,7]],[[3,2,8],[9,4,1]]])

In [30]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[3, 2, 8],
        [9, 4, 1]]])

In [31]:
arr3.ndim

3

In [34]:
arr3.shape #3 layer or 3 2-d, 2 row, 3 column

(3, 2, 3)

In [35]:
arr3.size

18

### Create random array

In [42]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.81007753, 0.84146322, 0.66022989],
        [0.76479281, 0.65240737, 0.40022587]],

       [[0.64333527, 0.75184417, 0.76424049],
        [0.79423984, 0.23514651, 0.63763846]],

       [[0.16408094, 0.04190926, 0.81363265],
        [0.46018345, 0.17309555, 0.51010402]]])

In [43]:
randomArr.dtype

dtype('float64')

In [45]:
zeroes=np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
zeroes.ndim

3

In [47]:
full= np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [50]:
ones= np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [51]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[3, 2, 8],
        [9, 4, 1]]])

In [53]:
arr3[0][0][0]

np.int64(4)

In [54]:
arr3[0][0]

array([1, 4, 5])

In [55]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [56]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [58]:
arr3[-1]

array([[3, 2, 8],
       [9, 4, 1]])

In [60]:
arr3[1][0][1]

np.int64(5)

In [61]:
arr3[1,0,1]

np.int64(5)

## Update & Delete

In [63]:
 a1=np.random.rand(2,3,2)
 a2=np.random.rand(2,3,2)

In [64]:
a1

array([[[0.88700324, 0.1553155 ],
        [0.83091724, 0.62877303],
        [0.2141456 , 0.48882704]],

       [[0.68608828, 0.60107313],
        [0.96851418, 0.98537601],
        [0.22718242, 0.77292531]]])

In [65]:
a2

array([[[0.70719333, 0.88756143],
        [0.19889278, 0.95126084],
        [0.5729411 , 0.14047214]],

       [[0.51761793, 0.85307453],
        [0.76467352, 0.95184827],
        [0.9819389 , 0.24213807]]])

#### Basic Math Operation

In [66]:
np.add(a1,a2) #numpy always function element wise

array([[[1.59419657, 1.04287693],
        [1.02981002, 1.58003388],
        [0.78708669, 0.62929918]],

       [[1.20370621, 1.45414766],
        [1.7331877 , 1.93722428],
        [1.20912132, 1.01506338]]])

In [67]:
np.subtract(a1,a2)

array([[[ 0.17980991, -0.73224593],
        [ 0.63202445, -0.32248781],
        [-0.3587955 ,  0.3483549 ]],

       [[ 0.16847035, -0.25200139],
        [ 0.20384065,  0.03352773],
        [-0.75475649,  0.53078725]]])

In [68]:
np.divide(a1,a2)

array([[[1.25425849, 0.17499127],
        [4.17771438, 0.66098909],
        [0.37376547, 3.47988598]],

       [[1.32547241, 0.70459627],
        [1.26657213, 1.03522382],
        [0.23136105, 3.1920851 ]]])

In [70]:
np.multiply(a1,a2)

array([[[0.62728277, 0.13785205],
        [0.16526344, 0.59812717],
        [0.12269281, 0.06866658]],

       [[0.35513159, 0.51276018],
        [0.74059715, 0.93792845],
        [0.22307925, 0.18715464]]])

## Statstical operations

In [71]:
sqrt=np.sqrt(25)
abs=np.abs(-2)
power=np.power(2,8)
log=np.log(25)
mins=np.min(a1)
max=np.max(a2)

In [72]:
sqrt

np.float64(5.0)

In [73]:
abs

np.int64(2)

In [74]:
power

np.int64(256)

In [75]:
log

np.float64(3.2188758248682006)

In [76]:
mins

np.float64(0.15531550192557186)

In [77]:
max

np.float64(0.9819389023036132)

## update

In [78]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[3, 2, 8],
        [9, 4, 1]]])

In [81]:
arr3[0,0,2]=9
arr3

array([[[1, 4, 9],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[3, 2, 8],
        [9, 4, 1]]])

In [83]:
arr3.sort()
arr3

array([[[1, 4, 9],
        [4, 6, 7]],

       [[3, 4, 5],
        [5, 7, 8]],

       [[2, 3, 8],
        [1, 4, 9]]])

## Reshape

In [84]:
arr3.shape

(3, 2, 3)

In [91]:
arr3_reshape = arr3.reshape((2,3,-1))
arr3_reshape

array([[[1, 4, 9],
        [4, 6, 7],
        [3, 4, 5]],

       [[5, 7, 8],
        [2, 3, 8],
        [1, 4, 9]]])

In [92]:
arr3_reshape.shape

(2, 3, 3)

## Appending and Inserting

In [93]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [94]:
new_array= np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [107]:
appd = np.append(zeroes, new_array, axis=0) #axis=0 => row, axis=1 => col
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

##### Insert 

In [101]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [102]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [105]:
inserted_array = np.insert(zeroes, 2, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [109]:
arr4= np.random.rand(3,2,3)
arr4

array([[[0.79638576, 0.78516668, 0.48549132],
        [0.58112421, 0.20186605, 0.566229  ]],

       [[0.07128829, 0.89314218, 0.19196356],
        [0.90400122, 0.38266249, 0.45852551]],

       [[0.29319937, 0.68263983, 0.03924449],
        [0.07792085, 0.03286082, 0.95099967]]])

In [110]:
arr5=np.delete(arr4,0,axis=1)
arr5

array([[[0.58112421, 0.20186605, 0.566229  ]],

       [[0.90400122, 0.38266249, 0.45852551]],

       [[0.07792085, 0.03286082, 0.95099967]]])

In [112]:
np.save("new_array", arr5)

In [113]:
np.load('new_array.npy')

array([[[0.58112421, 0.20186605, 0.566229  ]],

       [[0.90400122, 0.38266249, 0.45852551]],

       [[0.07792085, 0.03286082, 0.95099967]]])